<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_PatientDashboard</name>
   <tag></tag>
   <elementGuidId>db50025e-9630-456e-a7ed-17d285e38f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//svg[@data-testid='ArrowDropDownIcon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//svg[@data-testid='ArrowDropDownIcon']</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
