<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div2div4iframe1_c-ipkxrhqkuqo5</name>
   <tag></tag>
   <elementGuidId>d6feb9e6-a5ab-4cca-9af6-4cf0145ff84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-ipkxrhqkuqo5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-ipkxrhqkuqo5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-ipkxrhqkuqo5&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4a3f7f81-dcc0-40e8-948a-53d3b25c10d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>8241545b-8c26-49f0-b59c-eda229151466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-ipkxrhqkuqo5</value>
      <webElementGuid>cba39c94-3f41-444f-9fb7-aa854d8e825e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e41c3158-25e5-4747-baaf-63bec23cc01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>34f1c9b0-f577-4460-be05-c2a990a5f019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>a844ff62-c566-44e2-962c-1d74b0b9adf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA46AmPR_lSui2kvoUOyxGMKT3msgwvIY4S4TIB5FYk-9mPSPXuybom0AhCnObFGdDX1UHs5zMJKHFbARlji2JB24AI4Bw</value>
      <webElementGuid>23c825cc-a590-4f91-a0af-4e934c28fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>79624054-5ad6-4dbd-a99d-2e978c59d9f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-ipkxrhqkuqo5']</value>
      <webElementGuid>e8a81a57-d44e-4007-a17a-6aee4efda01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>663a4d28-6a4f-4a9b-9b6b-69a0ea4032c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-ipkxrhqkuqo5' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA46AmPR_lSui2kvoUOyxGMKT3msgwvIY4S4TIB5FYk-9mPSPXuybom0AhCnObFGdDX1UHs5zMJKHFbARlji2JB24AI4Bw']</value>
      <webElementGuid>4097990e-db90-4bdc-9a78-dbd07b06456a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
