<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-cfon1q9lyz3n</name>
   <tag></tag>
   <elementGuidId>2ee5eb9c-6c7c-4691-a9ed-00bee3e32f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-cfon1q9lyz3n']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-cfon1q9lyz3n&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-cfon1q9lyz3n&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cc73f50f-79f7-4f8c-8252-81fc8e6da615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4596bd6c-920a-44e7-b8c3-38ed264eabb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>1ed585a8-0689-475f-94c9-02c513c1ee16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>42599959-e2e3-40ca-89ea-92ae794aeeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6e0eb2f9-6ef6-41a2-81e5-685886d12d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-cfon1q9lyz3n</value>
      <webElementGuid>f9817a44-e611-4d2c-96fc-2b08836a81a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a451b8e-97a8-45e3-ba2d-20e6d50886dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b6c770c7-01ae-4272-8ca3-a9315dad4fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>00099f98-5bde-418d-ac0a-ebc1a97aa8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;co=aHR0cHM6Ly9kZWFjb25lc3MtZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=XrIDux0s7SoNe6_IHkjGC92W&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=2za2114bi1gp</value>
      <webElementGuid>a8edfdc9-0634-4a8b-bdc3-6102fc37405a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container css-17r26s3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item css-f068ot&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-3qgq5l&quot;]/form[1]/div[@class=&quot;MuiGrid-root MuiGrid-container css-12q1jqj&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>bbfa21e1-15ad-4999-85bd-ae8620c239fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-cfon1q9lyz3n']</value>
      <webElementGuid>4bdb458c-b140-442d-867d-37638c4e3f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/form/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>e398f741-d342-4665-9080-ccf4fca88f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5b0e8267-1af6-436c-b897-587ceea4040f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-cfon1q9lyz3n' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;co=aHR0cHM6Ly9kZWFjb25lc3MtZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=XrIDux0s7SoNe6_IHkjGC92W&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=2za2114bi1gp']</value>
      <webElementGuid>242fc385-619c-4d13-bf65-ae104a312172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
