<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div2div4iframe1_c-cgsk5cvurr6b</name>
   <tag></tag>
   <elementGuidId>1d1ce6c8-7637-4438-a73c-9d5a66f693f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-cgsk5cvurr6b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-cgsk5cvurr6b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-cgsk5cvurr6b&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d4e05040-7c4f-48be-a1b5-299563f58245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>4ea12602-0e22-4129-a6e2-d177785a39d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-cgsk5cvurr6b</value>
      <webElementGuid>736b16dd-072d-4749-8ba4-782e4b45baf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d14de5d7-4380-4f30-861a-d830f983858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2e7cc2f3-60b7-4d71-b2e6-262defa33219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>aa9ac436-a0d9-4c84-a196-829718a9920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA7YMTjsoG7z-QMz4dwlbtMnh1DWV8dagyMZZS_Ea1jTIrjMB3pDo6gJJIrdf9cJ3KGsBIvtXlBrheyzPV1wezvx-GzcNg</value>
      <webElementGuid>c9649872-a433-4db6-96b9-75d8a358b4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>7c15b063-85b3-4e34-8ce5-dac90034b304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-cgsk5cvurr6b']</value>
      <webElementGuid>18b59ec0-8520-4912-a2ef-77f65f30fdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>a0bd0fe6-71bc-45aa-a779-0f8a89648fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-cgsk5cvurr6b' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA7YMTjsoG7z-QMz4dwlbtMnh1DWV8dagyMZZS_Ea1jTIrjMB3pDo6gJJIrdf9cJ3KGsBIvtXlBrheyzPV1wezvx-GzcNg']</value>
      <webElementGuid>e8368a39-5661-4a9b-98ee-38d1ec1609fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
