<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-5zoubh618txs</name>
   <tag></tag>
   <elementGuidId>4f796d80-cbce-4b21-8156-73c13288f7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-5zoubh618txs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-5zoubh618txs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b76ce924-7f2f-4246-b05b-a9c8005549c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>7867cfea-e49c-4eff-b68d-99a115186982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>d803c279-831f-489b-91c8-3315726f4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e0c74df7-340a-4498-b1cf-7813a4f53ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4c4a7427-5784-48a2-bebd-c6254c2f5ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-5zoubh618txs</value>
      <webElementGuid>4dd30a16-67ac-4faa-b992-c707e79dd8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dffc9f54-1bad-4da9-a493-59d1b308e1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1d2349fc-d19a-4a6a-8135-c97ad32a1fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>550af1b9-4ea7-4634-a809-5aad1f773d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI&amp;co=aHR0cHM6Ly9jb21tdW5pdHktZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=TkacYOdEJbdB_JjX802TMer9&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=nmfec652o2gm</value>
      <webElementGuid>52f72c8e-18ee-48d0-bf15-fd85b32dd9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container css-17r26s3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item css-f068ot&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-3qgq5l&quot;]/form[1]/div[@class=&quot;MuiGrid-root MuiGrid-container css-12q1jqj&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>e3f00097-f9c9-4815-99b3-a628634a6671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-5zoubh618txs']</value>
      <webElementGuid>ab635eed-3a96-473c-8923-7aefd12ea484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/form/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>3e16f717-2c35-4a65-8755-a69a37379167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cc579103-ae22-4109-9907-2fb2f786daae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-5zoubh618txs' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI&amp;co=aHR0cHM6Ly9jb21tdW5pdHktZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=TkacYOdEJbdB_JjX802TMer9&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=nmfec652o2gm']</value>
      <webElementGuid>9f1028c1-54c7-4b34-b616-7d8a36d5f8a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
