<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressline1</name>
   <tag></tag>
   <elementGuidId>65c8954f-132d-45b2-8052-e6fb4aa6cb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressline1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressline1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc90791d-4c82-4848-b6d5-0c3d6e9e3825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>885922f0-e956-4a05-826e-60efdc49b32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressline1</value>
      <webElementGuid>9a512da2-89fe-47ce-8568-4c736a2b5e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressline1</value>
      <webElementGuid>3db1dcc6-6bde-4e66-9efb-80fd1f6b6d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9eec30ec-fe13-4c3c-a4bc-5ac695e00b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>57094193-dba4-4737-a3b0-006dbb281122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>4ad0531f-7499-44fc-8117-23a12b2b71b8</value>
      <webElementGuid>db882db9-c90c-4b9e-98b2-4e3f8bacb717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressline1&quot;)</value>
      <webElementGuid>29d852c0-3d9f-49cf-8d1b-cd9575555b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressline1']</value>
      <webElementGuid>8fa6a84d-eed9-40a4-813a-80c4bbf3a5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>39ee5201-bb19-454a-a2fd-ab6a73f6f6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1671cdf3-a7ef-4f15-b573-7237915197cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressline1' and @name = 'addressline1' and @type = 'text']</value>
      <webElementGuid>e05cbaf4-4740-43cc-b741-e53019f11fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
