<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_PotentialDuplicateYes_AtFirstRow</name>
   <tag></tag>
   <elementGuidId>fa8f92bc-55e3-4eb3-acd6-b4a5acc80f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='row'][1]//div[@data-field='potentialDuplicate']//span[text()='Yes']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
