<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form</name>
   <tag></tag>
   <elementGuidId>ab21eb85-07bb-4a7d-baba-58a0b64e08e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>2fd9808d-35a0-463d-97ff-3290e6a1bc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal Information* Required FieldsFirst Name *First Name *Middle NameMiddle NameLast Name *Last Name *Date of Birth *Date of Birth *Mobile NumberMobile NumberEmailEmailHospital Account RecordHospital Account RecordAdmittance DateAdmittance DateAre you a citizen of the USA? *Are you a citizen of the USA? *Social Security Number *Social Security Number *SSN is only required for US Citizens.Gender *Gender *Current AddressAddress *Address *Apartment, Suite, Etc.Apartment, Suite, Etc.City *City *State *State *Zip Code *Zip Code *Additional InformationDo you currently have health insurance, including Medicare or Medicaid? *YesNoDoes this visit relate to an accident? *YesNoAre you currently incarcerated? *YesNoWere you ever in foster care? *YesNoIn the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *YesNoIncome SourceYour income is an important part of your application. Please provide all sources of income.No Income SourceAdd Income SourceContinue</value>
      <webElementGuid>822b59d3-b85f-486f-aa13-f15c0bb18d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-101arav&quot;]/div[@class=&quot;MuiStack-root css-1phb13z&quot;]/form[1]</value>
      <webElementGuid>0d85f1b8-1920-49e8-86e9-786a65b67a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form</value>
      <webElementGuid>96f3fccd-3974-4a62-abea-82c9086180c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send PURL'])[1]/following::form[1]</value>
      <webElementGuid>e85aae0c-52c5-4dce-bb73-5fecfa01369f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::form[1]</value>
      <webElementGuid>6cd41468-df64-45f2-ac0a-2ef1d50839f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f108fdba-11d6-4815-af3d-bd85813e0e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Personal Information* Required FieldsFirst Name *First Name *Middle NameMiddle NameLast Name *Last Name *Date of Birth *Date of Birth *Mobile NumberMobile NumberEmailEmailHospital Account RecordHospital Account RecordAdmittance DateAdmittance DateAre you a citizen of the USA? *Are you a citizen of the USA? *Social Security Number *Social Security Number *SSN is only required for US Citizens.Gender *Gender *Current AddressAddress *Address *Apartment, Suite, Etc.Apartment, Suite, Etc.City *City *State *State *Zip Code *Zip Code *Additional InformationDo you currently have health insurance, including Medicare or Medicaid? *YesNoDoes this visit relate to an accident? *YesNoAre you currently incarcerated? *YesNoWere you ever in foster care? *YesNoIn the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *YesNoIncome SourceYour income is an important part of your application. Please provide all sources of income.No Income SourceAdd Income SourceContinue' or . = 'Personal Information* Required FieldsFirst Name *First Name *Middle NameMiddle NameLast Name *Last Name *Date of Birth *Date of Birth *Mobile NumberMobile NumberEmailEmailHospital Account RecordHospital Account RecordAdmittance DateAdmittance DateAre you a citizen of the USA? *Are you a citizen of the USA? *Social Security Number *Social Security Number *SSN is only required for US Citizens.Gender *Gender *Current AddressAddress *Address *Apartment, Suite, Etc.Apartment, Suite, Etc.City *City *State *State *Zip Code *Zip Code *Additional InformationDo you currently have health insurance, including Medicare or Medicaid? *YesNoDoes this visit relate to an accident? *YesNoAre you currently incarcerated? *YesNoWere you ever in foster care? *YesNoIn the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *YesNoIncome SourceYour income is an important part of your application. Please provide all sources of income.No Income SourceAdd Income SourceContinue')]</value>
      <webElementGuid>3d37b29a-9c94-499c-9a6b-121cebf5cecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
