<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressline1</name>
   <tag></tag>
   <elementGuidId>cb326da8-3cbc-4e9b-8c39-f7515b56eb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressline1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressline1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5fe937d-4001-4b23-9dde-9d59cbbea53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>847cad34-0eba-4bde-831b-054427b1b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressline1</value>
      <webElementGuid>f988d81c-c245-418b-bed7-63bc31801a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7915791-9f6f-4671-a440-9ab9c4caa4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>0bd028ef-1096-438a-808a-7338baadceae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>e9696485-d3a2-4b1b-9b9d-4643fc05fb3f</value>
      <webElementGuid>d10f56b5-f257-424a-997d-57e536df3034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressline1&quot;)</value>
      <webElementGuid>385f3f32-2f7a-4b7e-bc43-93827a9e6220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressline1']</value>
      <webElementGuid>c87e090b-64c3-4c5c-96ca-482fcbf7476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>37793140-9b7c-4f56-b840-0b52cd14f2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6a93826f-816f-4994-a8c9-b5927bc3c8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressline1' and @type = 'text']</value>
      <webElementGuid>1cb897cf-0447-42ce-9680-e1f74a2d8c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
