<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No_lost-health-insurance-label</name>
   <tag></tag>
   <elementGuidId>0e3b9e1c-5220-4dad-8d3d-bdf061953da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lost-health-insurance-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lost-health-insurance-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>52695f60-8e1c-43f4-b6a0-5a21c7396f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>ce6c3c1a-38a0-4806-b6d6-13fb0909f185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lost-health-insurance-label</value>
      <webElementGuid>10aedc73-2eb0-4c72-a544-cb0964d3961a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *</value>
      <webElementGuid>effb6921-b30d-4686-94e9-ba7960566f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lost-health-insurance-label&quot;)</value>
      <webElementGuid>360839b6-3145-40d2-83b8-6aab36263a2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lost-health-insurance-label']</value>
      <webElementGuid>12f22a2b-017f-4ae1-8ea8-000c6e88fc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[3]/div/div[5]/div/label</value>
      <webElementGuid>1a2a9b8a-dc0f-4c7d-b18d-9035b9e08dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::label[1]</value>
      <webElementGuid>7931ff3e-80a4-4ab6-80a8-877cde660426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[4]/following::label[2]</value>
      <webElementGuid>cea4e6ce-5229-4a8f-a15c-c36c3a3b536d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[5]/preceding::label[1]</value>
      <webElementGuid>4560cf9e-6454-4faa-add9-69815e400cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[5]/preceding::label[2]</value>
      <webElementGuid>085d8210-f651-4ac2-a549-dec16d4bf2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='In the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance?']/parent::*</value>
      <webElementGuid>ccaca571-b685-4917-a9a5-d49f34b9f902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/label</value>
      <webElementGuid>2a9b2137-bdbf-4c05-ada0-fdf77827f6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lost-health-insurance-label' and (text() = 'In the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *' or . = 'In the last 60 days or the upcoming 60 days, have you lost, or will you lose health insurance? *')]</value>
      <webElementGuid>8ffa1fc7-f34b-4b37-99d3-21ce588f8e7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
